pkg/yarn/parse.go
=> delete debug lines and add comments

pkg/poetry/parse.go, pkg/poetry/parse_test.go, pkg/poetry/parse_testcase.go, pkg/poetry/testdata/poetry_flask.lock, pkg/poetry/testdata/poetry_many.lock, pkg/poetry/testdata/poetry_normal.lock
Create poetry parser for Python support!
=> Add poetry parser

go.mod, pkg/bundler/parse.go, pkg/bundler/parse_test.go, pkg/bundler/parse_testcase.go, pkg/cargo/parse.go, pkg/cargo/parse_test.go, pkg/cargo/parse_testcase.go, pkg/composer/parse.go, pkg/composer/parse_test.go, pkg/composer/parse_testcase.go, pkg/npm/parse.go, pkg/npm/parse_test.go, pkg/npm/parse_testcase.go, pkg/pipenv/parse.go, pkg/pipenv/parse_test.go, pkg/pipenv/parse_testcase.go, pkg/poetry/parse.go, pkg/poetry/parse_test.go, pkg/poetry/parse_testcase.go, pkg/yarn/parse.go, pkg/yarn/parse_test.go, pkg/yarn/parse_testcase.go
From knqyf263 to aquasecurity.
=> Transfer repositoriy

go.mod, go.sum, pkg/jar/log.go, pkg/jar/parse.go, pkg/jar/parse_test.go, pkg/log/log.go
use [go-retryablehttp](https://github.com/hashicorp/go-retryablehttp)
=> feat(jar): retry http accesses

pkg/jar/parse.go
proposing to change the base url to https for increased security and TLS encryption
=> changing base url to https

pkg/wheel/parse.go, pkg/wheel/parse_test.go, pkg/wheel/parse_testcase.go, pkg/wheel/testdata/distlib-0.3.1.METADATA, pkg/wheel/testdata/simple-0.1.0.METADATA, pkg/wheel/testdata/virtualenv-20.4.2.METADATA
Resolves aquasecurity/trivy#716
=> feat(python): add wheel support

pkg/types/types.go
This commit resolves the failing unit test related to FScache putblob
operation in Fanal test pipeline.
=> fix(types): add omitempty to License

pkg/egg/parse_test.go, pkg/wheel/parse_testcase.go
Removed sed commands in egg & wheel parser.
=> refactor(egg/wheel): change the comments

pkg/golang/binary/exe.go
=> refactor(go/binary): define a custom error

pkg/dotnet/core_deps/parse.go, pkg/dotnet/core_deps/parse_test.go, pkg/dotnet/core_deps/testdata/ExampleApp1.deps.json, pkg/dotnet/core_deps/testdata/InvalidJson.deps.json, pkg/dotnet/core_deps/testdata/NoLibraries.deps.json
Add support for dotnet core .deps.json files
Fixes https://github.com/aquasecurity/go-dep-parser/issues/102
=> feat(dotnet): Add support for parsing .Net core .deps.json files

pkg/nodejs/pnpm/parse.go, pkg/nodejs/pnpm/parse_test.go, pkg/nodejs/pnpm/parse_testcase.go, pkg/nodejs/pnpm/testdata/pnpm-lock_many.yaml, pkg/nodejs/pnpm/testdata/pnpm-lock_normal.yaml, pkg/nodejs/pnpm/testdata/pnpm-lock_with_dev.yaml
Hey, this PR is ~~a draft~~ for adding a pnpm parser. I know that there is other open but there seems to be no progress so I wanted to offer my solution. I hope it doesn't matter.
The issue is #65 
What I think is missing:
- ~~Add detection of direct / indirect dependencies~~
- ~~Add more tests~~
Doubts I have:
- Should the dev vulnerabilities be ignored?
If you think there is anything else I should consider, let me know. I want to try to finish it this week.
=> feat: add pnpm parser

pkg/c/conan/parse.go, pkg/c/conan/parse_test.go, pkg/c/conan/testdata/happy2.lock
This adds support for recipe revisions inside the Conan parser.
=> Fix #131. Support revisions in Conan parser

pkg/java/pom/pom.go
Fix mistake after #136 with value for len func after updating(#135) exclusion struct.
=> fix(pom): fix mistake with value for len func after updating exclusion struct

pkg/dotnet/core_deps/parse.go, pkg/dotnet/core_deps/parse_test.go
Add support dependency location for dotnet-core
=> feat(dotnet-core): add support dependency location for dotnet-core

pkg/python/pipenv/parse.go, pkg/python/pipenv/parse_testcase.go
Add dependency locations for `Pipfile.lock`
=> feat(pipenv): add dependency locations for Pipfile.lock

pkg/nodejs/packagejson/parse.go, pkg/nodejs/packagejson/parse_test.go
Add package id for `package.json` files
=> feat(packagejson): add package id

pkg/python/pyproject/pyproject.go, pkg/python/pyproject/pyproject_test.go, pkg/python/pyproject/testdata/happy.toml
Should help fixing aquasecurity/trivy#3720
=> Support for optional dependencies in pyproject

pkg/nodejs/packagejson/parse.go, pkg/nodejs/packagejson/parse_test.go, pkg/nodejs/packagejson/testdata/package.json, pkg/types/types.go
We need dependencies from `package.json` files to update dependencies from `yarn.lock` files.
=> feat(packagejson): parse dependencies/optionalDependencies

pkg/nodejs/packagejson/parse.go, pkg/nodejs/packagejson/parse_test.go, pkg/nodejs/packagejson/testdata/package.json
Trivy needs to know about workspaces to analyze them.
See https://github.com/aquasecurity/trivy/issues/4633
=> feat(nodejs): add the workspaces field to the package

pkg/c/conan/parse.go, pkg/c/conan/parse_test.go
Add locations for `conan` dependencies.
=> feat(conan): add locations

pkg/swift/swift/parse.go, pkg/swift/swift/parse_test.go
Add `ID` field for swift `Package.resolved` files.
=> fix(swift): add ID field

pkg/java/pom/artifact.go, pkg/java/pom/parse.go, pkg/java/pom/parse_test.go, pkg/java/pom/testdata/repository/org/example/example-api/1.7.30/example-api-1.7.30.pom, pkg/java/pom/testdata/repository/org/example/example-api/2.0.0/example-api-2.0.0.pom
Add licenses extracted from the pom to the artifact
See https://github.com/aquasecurity/trivy/issues/5028
=> fix(java): add licenses to artifact

go.mod, go.sum
=> chore(deps): bump Go to 1.21

pkg/gradle/lockfile/parse.go, pkg/gradle/lockfile/parse_test.go
Add dependency location support
- aquasecurity/trivy/issues/5948
=> feat(gradle): add dependency location support
