aquasecurity/go-dep-parser

pkg/yarn/parse.go
pkg/yarn/parse_test.go

fix parse bug on yarn.lock.
ie) `"jquery@git+https://xxxx:x-oauth-basic@github.com/tomoyamachi/jquery":`
https://github.com/knqyf263/trivy/issues/39#issuecomment-494365349

fixbug : parse private versioning yarn.lock

---

pkg/jar/parse.go
pkg/jar/parse_test.go

This would enable the embedder of this library to decide whether to allow or disallow network calls to maven central. Those who don't want the remote call shall pass dummy client.
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>

fix: add an option to override http.Client used by jar parser

---

pkg/gomod/parse.go
pkg/gomod/parse_test.go
pkg/gomod/parse_testcase.go
pkg/gomod/testdata/gomod_emptyline.sum

https://github.com/aquasecurity/trivy/issues/1004
```
panic: runtime error: index out of range [1] with length 0
goroutine 7430 [running]:
github.com/aquasecurity/go-dep-parser/pkg/gomod.Parse(0x22792e0, 0xc000b929c0, 0x10f8117, 0xc0003d2a90, 0xc00017e180, 0x2b, 0x80)
/Users/teppei/pkg/mod/github.com/aquasecurity/go-dep-parser@v0.0.0-20210427143403-3c97ccc53976/pkg/gomod/parse.go:23 +0x56f
github.com/aquasecurity/fanal/analyzer/library.Analyze(0x2075788, 0x5, 0xc0000419b0, 0x2a, 0xc00096ac00, 0x153, 0x200, 0x20cb358, 0x200, 0x20cb350, ...)
/Users/teppei/src/github.com/aquasecurity/fanal/analyzer/library/analyze.go:18 +0x93
github.com/aquasecurity/fanal/analyzer/library/gomod.gomodAnalyzer.Analyze(0xc0000419b0, 0x2a, 0xc00096ac00, 0x153, 0x200, 0x0, 0x0, 0x0) …
```

fix(gomod): skip an empty line

---

pkg/gobinary/parse.go
pkg/gobinary/parse_test.go

I updated the gobinary line checking logic to understand replace directive("=>") and also added ability to understand lines without hash values.
I do not know why i do not get hash values when i build binary in a container with vendor folder but you can find the steps in [this repo](https://github.com/ebati/trivy-mod-parse). The test binary (replace.elf) is also from the code in that repo.
Related to aquasecurity/trivy/issues/980

fix(gobinary): check first column to determine meaning

---

pkg/nodejs/npm/parse_testcase.go
pkg/nodejs/yarn/parse.go
pkg/nodejs/yarn/parse_test.go
pkg/nodejs/yarn/parse_testcase.go
pkg/nodejs/yarn/testdata/yarn_with_npm.lock

npm v7 supports `yarn.lock` as well as `package-lock.json`. Also, it updates `yarn.lock`. But the format is different from the original one.
Each key is not quoted as below.
```
$ yarn init -y
$ yarn add jquery
$ cat yarn.lock
jquery@^3.6.0:
version "3.6.0"
resolved "https://registry.yarnpkg.com/jquery/-/jquery-3.6.0.tgz#c72a09f15c1bdce142f49dbf1170bdf8adac2470"
integrity sha512-JVzAR/AjBvVt2BmYhxRCSYysDsPcssdmTFnzyLEts9qNwmjmu4JTAMYubEfwVOSwpQ1I1sKKFcxhZCI2buerfw==
```
On the other hand, once`npm` updates `yarn.lock`, keys are double-quoted.
```
$ npm install
/app # cat yarn.lock
"jquery@^3.6.0":
"integrity" "sha512-JVzAR/AjBvVt2BmYhxRCSYysDsPcssdmTFnzyLEts9qNwmjmu4JTAMYubEfwVOSwpQ1I1sKKFcxhZCI2buerfw=="
"resolved" "https://registry.npmjs.org/jquery/-/jquery-3.6.0.tgz"
"version" "3.6.0" …
```

 fix(yarn): support quoted version

---

pkg/python/pip/parse.go
pkg/python/pip/parse_test.go
pkg/python/pip/parse_testcase.go
pkg/python/pip/testdata/requirements_hash.txt

[Hash-Checking Mode](https://pip.pypa.io/en/stable/cli/pip_install/#hash-checking-mode) available in pip since version 8.0 causes the current pip parser to fail, this will fix the pip parsing
Fixes https://github.com/aquasecurity/fanal/issues/323

fix(python): fix parsing of requirements.txt with hash checking mode available in pip since version 8.0

---

pkg/golang/binary/exe.go
pkg/golang/binary/parse.go
pkg/io/io.go

Do not use ioutil.ReadAll() for improving performance.

fix(go/binary): avoid reading all

---

go.mod
go.sum
pkg/java/pom/artifact.go
pkg/java/pom/parse.go
pkg/java/pom/parse_test.go
pkg/java/pom/testdata/version-requirement/pom.xml

We support only the first two requirements. Other requirements should be skipped at the moment.

fix(java/pom): ignore unsupported requirements

---

pkg/python/pip/parse.go
pkg/python/pip/parse_test.go
pkg/python/pip/parse_testcase.go
pkg/python/pip/testdata/requirements_hyphens.txt

Changed getting the index of the first instance of substr instead of the index of the first instance of any Unicode code point from chars.
Fixes #81

fix(pip): handling a package name with a hyphen

---

pkg/java/pom/parse.go
pkg/java/pom/parse_test.go
pkg/java/pom/testdata/repository/org/example/example-dependency2/2.3.4/example-dependency2-2.3.4.pom
pkg/java/pom/testdata/soft-requirement-with-transitive-dependencies/pom.xml

In Maven, an order of `<dependencies>` is critical. If the order is updated, the resolved dependencies will be different. The current implementation uses a map that doesn't keep order. This PR fixes the issue.
- dependency-a
- dependency-c v1
- dependency-b
- dependency-c v2
If the soft requirement is used, `v1` should be used for `dependency-c`.
- dependency-b
- dependency-c v2
- dependency-a
- dependency-c v1
On the other hand, `v2` should be used in the above case.
https://github.com/aquasecurity/trivy/issues/1728
https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification

fix(pom): keep an order of dependencies

---

pkg/java/jar/parse.go

This should allow setting the URL which go-dep-parser uses to contact Maven Central when parsing JAR dependencies. It's an attempt to provide a solution for https://github.com/aquasecurity/trivy/issues/1869. I haven't developed in go before so not sure if this is a bad attempt or not :sweat_smile:

feat(jar): Allow setting Maven Central URL using environment variable

---

pkg/java/pom/parse.go
pkg/java/pom/parse_test.go
pkg/java/pom/testdata/import-dependency-management-multiple/pom.xml
pkg/java/pom/testdata/repository/org/example/example-dependency-management2/1.1.1/example-dependency-management2-1.1.1.pom

In maven, a definition of a dependency will not override by any other definition.
```
% mvn -s testdata/conf/settings.xml -f testdata/import-dependency-management-multiple dependency:tree  | grep example-api
[ERROR] Failed to execute goal on project import: Could not resolve dependencies for project com.example:import:pom:2.0.0: org.example:example-api:jar:1.7.30 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```
Previously, go-dep-parser detects version 1.1.1, since its defined in the second import bom.
See also: https://github.com/aquasecurity/trivy/issues/1943

Fix merge multiple pom imports

---

pkg/golang/mod/parse.go
pkg/golang/mod/parse_test.go
pkg/golang/mod/parse_testcase.go
pkg/golang/mod/testdata/no-go-version/go.mod
pkg/golang/mod/testdata/no-go-version/main.go

We have panic, if go.mod doesn't contain go version.:
```
➜  cat go.mod 
module github.com/aquasecurity/fanal                                          
➜  trivy fs .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16ee9bc]
goroutine 38 [running]:
github.com/aquasecurity/go-dep-parser/pkg/golang/mod.Parse({0x2224da0, 0xc000a5a2e8})
/home/runner/go/pkg/mod/github.com/aquasecurity/go-dep-parser@v0.0.0-20220412145205-d0501f906d90/pkg/golang/mod/parse.go:29 +0x13c
github.com/aquasecurity/fanal/analyzer/language.Analyze({0x1d16263, 0x5}, {0xc000fbb9c0, 0x6}, {0x2224da0?, 0xc000a5a2e8?}, 0x0?)
/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220414083417-61bfa9f92483/analyzer/language/analyze.go:1 …
```

fix: fixed panic for gomod without version

---

pkg/nodejs/packagejson/parse.go
pkg/nodejs/packagejson/parse_test.go

This change introduced a bug. Seems like `repository` can be string. We need to revert it for now and take a further investigation later.
```
2022-08-15T19:24:58.636+0600    DEBUG   Analysis error: unable to parse var/www/html/package.json: JSON decode error: json: cannot unmarshal string into Go struct field packageJSON.repository of type packagejson.packageRef
2022-08-15T19:25:00.080+0600    INFO    Number of language-specific files: 3
2022-08-15T19:25:00.081+0600    INFO    Detecting composer vulnerabilities...
2022-08-15T19:25:00.082+0600    DEBUG   Detecting library vulnerabilities, type: composer, path: var/www/html/composer.lock
2022-08-15T19:25:00.084+0600    DEBUG   Detecting library vulnerabilities, type: composer, path: …
```

revert references in package.json

---

pkg/java/pom/parse_test.go
pkg/ruby/gemspec/parse.go
pkg/ruby/gemspec/testdata/multiple_licenses.gemspec

There are licenses like `"Apache 2.0".freeze`. 
We incorrectly split this license as `Apache` and `2.0.freeze`.
Changed separator to `,`.

fix(gemspec): split licenses by ', '

---

pkg/rust/binary/parse.go
pkg/rust/binary/parse_test.go

There was skipped package IDs, so `trivy` can't match dependencies

fix(rust): add skipped package IDs

---

pkg/gradle/lockfile/parse.go
pkg/gradle/lockfile/parse_test.go
pkg/gradle/lockfile/testdata/empty.lockfile
pkg/gradle/lockfile/testdata/happy.lockfile

Add [*gradle.lockfile](https://docs.gradle.org/current/userguide/dependency_locking.html#lock_state_location_and_format) parser.
- aquasecurity/trivy/issues/2707

feat(gradle): add *gradle.lockfile parser

---

pkg/java/pom/pom.go
pkg/java/pom/testdata/exclusions/pom.xml

When we unmarshal `pom.xml` file, we only keep the last `exclusion` for each dependency.
Fixed it.
- https://github.com/aquasecurity/trivy/issues/2920

fix(pom): fix unmarshal exclusions

---

pkg/java/pom/parse.go
pkg/java/pom/parse_test.go
pkg/java/pom/pom.go
pkg/java/pom/testdata/upper-pom-dep-management/pom.xml

Non-empty fields of dependency(if child pom.xml has this dependency) from `DependencyManagement` from upper pom.xml have higher priority then dependency fields from `Dependency` from child pom.xml.
Example:
Base pom.xml:
```xml
<dependencyManagement>
<dependencies>
<dependency>
<groupId>org.jetbrains</groupId>
<artifactId>markdown-jvm</artifactId>
<version>0.2.2</version>
</dependency>
</dependencies>
</dependencyManagement>
<dependencies>
<dependency>
<groupId>org.jetbrains.dokka</groupId>
<artifactId>dokka-core</artifactId>
<version>1.7.10</version>
</dependency>
</dependencies>           
```
[org.jetbrains.dokka:dokka-core v1.7.10](https://repo1.maven.org/maven2/org/jetbrains/dokka/dokka-core/1.7.10/dokka-core-1.7.10.pom):
```xml
<dependencies>
<dependency> …
```

fix(java): use fields of dependency from dependencyManagement from upper pom.xml to parse deps

---

pkg/java/jar/parse.go

When we found wrong inner jar - we don't need to stop parsing jar.
We need to create debug message and continue parsing.
- aquasecurity/trivy/issues/2952

refactor(jar): write debug message when wrong inner jar is found

---

pkg/golang/binary/parse.go

Binaries with old go version may incorrectly add module in Deps.
e.g.:
Skip dependencies without `Path`.
- aquasecurity/trivy/issues/3237

fix(go): skip dep without Path for go-binaries

---

pkg/nodejs/yarn/parse.go
pkg/nodejs/yarn/parse_test.go
pkg/nodejs/yarn/testdata/bad_yarn.lock

Found an issue when failed to parse a dependency block:
[This](https://github.com/aquasecurity/go-dep-parser/blob/main/pkg/nodejs/yarn/parse.go#L214) line causes the scanner to return a result altho it should've thrown an error.

fix(yarn): yarn parser error handling

---

pkg/nodejs/yarn/parse.go

Fixed a trivy issue https://github.com/aquasecurity/trivy/issues/3428
Added more protocols to the ignore list and more details in the parse error.
For reference: https://yarnpkg.com/features/protocols

fix(yarn): ignore more protocols

---

pkg/java/jar/parse.go

Add `implementationVendor` and `specificationVendor` fields to detect GroupID from MANIFEST.MF.
Related Issues:

feat(java): add implementationVendor and specificationVendor fields to detect GroupID from MANIFEST.MF

---

pkg/nodejs/yarn/parse.go
pkg/nodejs/yarn/parse_test.go
pkg/nodejs/yarn/parse_testcase.go
pkg/nodejs/yarn/testdata/bad_yarn.lock
pkg/nodejs/yarn/testdata/yarn_with_bad_protocol.lock

We currently stop parsing if invalid protocol is found.
We need to show warning and continue parsing in these cases.

refactor: use warning for invalid protocols in yarn.lock

---

pkg/java/jar/parse.go

The inner separator in ZIP files is always slashed even though it is created on Windows.
https://github.com/aquasecurity/trivy/pull/3992#discussion_r1174786549

fix(jar): use slash as separator for any OS for inner jars

---

pkg/python/pip/parse.go
pkg/python/pip/parse_test.go
pkg/python/pip/parse_testcase.go
pkg/python/pip/testdata/requirement_exstras.txt

`requirement.txt` can contain extras. e.g. `pyjwt[crypto]==2.1.0`
We need to find dependency name correctly.

fix(pip): remove extras from lines of requirement.txt files

---

pkg/java/pom/parse.go
pkg/java/pom/parse_test.go

Following the issue described at https://github.com/aquasecurity/trivy/issues/3747 where for the case where you run :
trivy fs pom.xml 
with the following pom.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
<dependencies>
<dependency>
<groupId>org.apache.hive</groupId>
<artifactId>hive-exec</artifactId>
<version>2.3.3</version>
</dependency>
</dependencies>
</project>
```
you get zero results due to a parser error of one of the dependencies in the pom.
The following PR suggests skipping those missing modules.

fix(pom): skipping missing modules

---

pkg/nodejs/packagejson/parse.go
pkg/nodejs/packagejson/parse_test.go
pkg/nodejs/packagejson/testdata/without_version_package.json

`Name` and `Version` fields are optional for `package.json` - https://docs.npmjs.com/cli/v9/configuring-npm/package-json#name
We don't need to return error for files without `name` or `version`.
- aquasecurity/trivy/issues/4054

refactor: don't return error for package.json without version/name

---

pkg/java/pom/parse.go
pkg/java/pom/parse_test.go
pkg/java/pom/testdata/wildcard-exclusions/pom.xml

`Maven` supports wildcards in `Exclusion` fields - https://maven.apache.org/pom.html#exclusions.
But i have playing with it and looks like `Maven` only supports `*` value. So i added logic only for `*` value.
For example this doesn't work:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>example</groupId>
<artifactId>trivy-test</artifactId>
<version>1.0-SNAPSHOT</version>
<dependencies>
<dependency>
<groupId>org.springframework.ws</groupId>
<artifactId>spring-ws-core</artifactId>
<version>3.0.1.RELEASE</version>
<exclusions>
<exclusion> …
```

fix(pom): add support of `*` for exclusions

---

pkg/java/pom/pom.go

Fixes: #226 
In the test that fails, one of the dependencies refers to the property `${project.version}`. The project properties are built [here](https://github.com/aquasecurity/go-dep-parser/blob/main/pkg/java/pom/pom.go#L47), but the iteration on the map is random. If the current properties are as follows:
```
{
"artifactId": "top-parent",
"groupId": "com.example",
"parent.artifactId": "",
"parent.groupId": "",
"parent.relativePath": "",
"parent.version": "",
"project.artifactId": "top-parent",
"project.groupId": "com.example",
"project.parent.artifactId": "",
"project.parent.groupId": "",
"project.parent.relativePath": "",
"project.parent.version": "",
"project.version": "3.0.0",
"version": "2.0.0"
}
```
then project.version can be 2.0.0 or 3.0.0 (depends on the order).
This also …

fix(java): do not overwrite properties

---

.gitignore
pkg/java/pom/artifact.go
pkg/java/pom/parse.go
pkg/java/pom/parse_test.go
pkg/java/pom/pom.go
pkg/java/pom/testdata/happy/pom.xml
pkg/java/pom/testdata/multiply-licenses/pom.xml

At the moment, the licenses specified in pom.xml , do not parse
- https://github.com/aquasecurity/trivy/issues/3812

feat(java): capture licenses from pom.xml

---

pkg/java/pom/parse.go
pkg/java/pom/parse_test.go
pkg/java/pom/pom.go
pkg/java/pom/testdata/parent-version-is-property/child/pom.xml
pkg/java/pom/testdata/parent-version-is-property/pom.xml
pkg/java/pom/utils.go

There is case when parent version is property (e.g. `${revision}`). We need to try find of this parent by relative path.
More information [here](https://github.com/aquasecurity/trivy/discussions/4670)

fix(pom): don't skip parent when version is property

---

pkg/python/packaging/parse.go
pkg/python/packaging/parse_test.go
pkg/python/packaging/testdata/iniconfig-2.0.0.METADATA
pkg/python/packaging/testdata/networkx-3.0.METADATA
pkg/python/packaging/testdata/zipp-3.12.1.METADATA
pkg/types/types.go

`License` field is deprecated and replaced by the new `License-Expression` field, and there was added `License-File` field.
Read more here [PEP 639 – Improving License Clarity with Better Package ](https://peps.python.org/pep-0639/#deprecate-license-field).
also there are legacy packages that use license classifiers (`Classifier` field), so we have to check it too.

feat(python): add license fields

---

pkg/nodejs/npm/parse.go
pkg/nodejs/npm/parse_test.go
pkg/nodejs/npm/parse_testcase.go
pkg/nodejs/npm/testdata/package-lock_v3_without_root_deps_field.json

There is case when root `Dependencies` field (packages[""].Dependencies) is `nil`.
We need initialize this map to insert direct dependencies from links.
- https://github.com/aquasecurity/trivy/issues/4923

fix(npm): add init of root deps

---

pkg/swift/cocoapods/parse.go
pkg/swift/cocoapods/parse_test.go

`Purl` uses `@` to separate package name and version - https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#cocoapods
Use same logic.

refactor(cocoapods): use `utils.PackageID` for ID

---

pkg/java/pom/artifact.go
pkg/java/pom/parse.go
pkg/java/pom/parse_test.go
pkg/java/pom/testdata/hard-requirement/pom.xml
pkg/java/pom/testdata/multi-module/module/pom.xml
pkg/java/pom/testdata/repository/org/example/example-nested/3.3.4/example-nested-3.3.4.pom
pkg/java/pom/utils.go

Add `ID` and `dependsOn` support.
Fill `Indirect` field.
Some nuances:
- root/module artifact is marked as `Direct`.
- dependencies of root/module artifact are marked as `Direct` (this is necessary to be able to exclude indirect dependencies from Trivy report - https://github.com/aquasecurity/trivy/discussions/4870).
- root artifact doesn't contains modules in `dependsOn` (see more [here](https://github.com/DmitriyLewen/go-dep-parser/blob/bb82a5149a74ed72accd9a8a171cb08e4378f15e/pkg/java/pom/parse_test.go#L661-L691))
- Close #126
- aquasecurity/trivy/issues/3272

feat(pom.xml): add `dependsOn` and `Indirect` support

---

pkg/python/packaging/parse.go
pkg/python/packaging/parse_test.go
pkg/python/packaging/testdata/unidecode-egg-info.PKG-INFO

`Golang` updated net/textproto package - https://cs.opensource.google/go/go/+/a6642e67e16b9d769a0c08e486ba08408064df19
After that we get error if MIME key or values contain bytes non-allowed by RFC 7230.
But if required fields (`name` and `version` in this case) found - we don't need to stop parsing.
Related Issues:
- aquasecurity/trivy/issues/5335

fix(python-packaging): skip MIME error, if name and version found

---

pkg/java/pom/parse.go
pkg/java/pom/parse_test.go
pkg/java/pom/testdata/no-parent-infinity-loop/parent/pom.xml
pkg/java/pom/testdata/no-parent-infinity-loop/pom.xml

We need to compare `ArtifactID`s for base and parent pom's when `relativePath == ../pom.xml` is used.
it is needed to avoid cases when we get incorrect parent or get infinity loop (if `../pom.xml` is scanned pom.xml).
We can inherit `GroupID`. Also `Version` can contains property.
So we need to compare only `ArtifactID`.
New test contains simple example - https://github.com/DmitriyLewen/go-dep-parser/blob/7d2c865da8912f9f3ea475cc94da61c819dcae0d/pkg/java/pom/parse_test.go#L987-L999
Example from real life - aquasecurity/trivy/discussions/5445
- aquasecurity/trivy/issues/5453

fix(pom): compare ArtifactIDs for base and parent pom's when `relativePath` field is used

---

pkg/java/jar/parse.go
pkg/java/jar/sonatype/sonatype.go

Add version to `SearchByArtifactID` function (for [Client](https://github.com/aquasecurity/go-dep-parser/blob/fc7f2b470d8926796902748479355ac92e153aaa/pkg/java/jar/parse.go#L27-L31) interface) so that you can get the GroupId with only the required version.
See aquasecurity/trivy/issues/5627

feat(jar): add version for SearchByArtifactID function

---

pkg/utils/utils.go
pkg/utils/utils_test.go

We need to check (and not overwrite) `Dev` field when retrieving uniq libs (`utils.UniqueLibraries` function).
See aquasecurity/trivy/issues/5532 for more details.

fix: check Dev field for UniqueLibraries func

---

pkg/java/pom/parse_test.go
pkg/java/pom/pom.go
pkg/java/pom/testdata/exclusions-in-child/pom.xml
pkg/java/pom/testdata/repository/org/example/example-exclusions/4.0.0/example-exclusions-4.0.0.pom

Fixed cases where we were removing excluded deps from upper pom's.
Example - https://github.com/aquasecurity/trivy/issues/5827
Test to better understand the fix - https://github.com/aquasecurity/go-dep-parser/blob/bf1b2d1cb5f5ad139c03d378674969ecd410d335/pkg/java/pom/parse_test.go#L689-L725

fix(pom): don't remove excluded deps from upper pom's

---

pkg/java/pom/artifact.go
pkg/java/pom/parse.go
pkg/java/pom/parse_test.go
pkg/java/pom/pom.go
pkg/java/pom/testdata/parent-properties/pom.xml

Add support of line numbers for deps from base pom.xml.
This PR doesn't add line numbers for:
- dependencies from parents
- dependencies for modules
- aquasecurity/trivy/issues/5945

feat(pom): add support of line numbers for deps from base pom.xml

---

pkg/nodejs/pnpm/parse.go
pkg/nodejs/pnpm/parse_testcase.go
pkg/nodejs/pnpm/testdata/pnpm-lock_archives.yaml

Dependency name may be present in `dependencyPath` or `Name` field - https://github.com/pnpm/spec/blob/274ff02de23376ad59773a9f25ecfedd03a41f64/lockfile/6.0.md#packagesdependencypathname
Same for Versions.
So we can check `Name` and `Version` fields instead of checking`Resolution`.
- aquasecurity/trivy/issues/6032

fix(pnpm): use `Name` and `Version` fields if present
